# **Tic-Tac-Toe Game**

*Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this Project, we will use the tools to create a tic-tac-toe simulator and evaluate basic winning strategies.*

*In this Project, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.*

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.
Create a function place(board, player, position), where:

- player is the current player (an integer 1 or 2).

- position is a tuple of length 2 specifying a desired location to place their marker.

In [2]:
import numpy as np

def create_board():
    board = np.zeros((3,3), dtype=int)
    return board
def place(board, player, position):
    if board[position] == 0:
        board[position] = player
        return board

board = create_board()
place(board, 1, (0, 0))        
    

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Write a function random_place(board, player) that places a marker for the current player at random among all the available positions (those currently set to 0).
Find possible placements with possibilities(board).
Select one possible placement at random using random.choice(selection).

In [3]:
def possibilities(board):
    not_occupied = np.where(board == 0)
    return list(zip(not_occupied[0], not_occupied[1]))

import random
random.seed(1)

def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

random_place(board, 2)

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

We will now have both players place three markers each.
A new board is given by the sample code. Call random_place(board, player) to place three pieces each on board for players 1 and 2.
Print board to see your result.

In [4]:
random.seed(1)
board = create_board()

for i in range(3):
    for player in [1, 2]:
        random_place(board, player)

print(board)

[[2 2 1]
 [0 1 0]
 [0 1 2]]


Make a function row_win(board, player) that takes the player (integer) and determines if any row consists of only their marker.

Have it return True if this condition is met and False otherwise.

Note that board is already defined. Call row_win to check if Player 1 has a complete row.

In [5]:
def row_win(board, player):
    if np.any(np.all(board==player, axis=1)): # this checks if any row contains all positions equal to player.
        return True
    else:
        return False

row_win(board, 1)

False

Make a function col_win(board, player) that takes the player (integer) and determines if any column consists of only their marker.

Have it return True if this condition is met and False otherwise.

Note that board is already defined as in Exercise 5. Call col_win to check if Player 1 has a complete column

In [6]:
def col_win(board, player):
    if np.any(np.all(board==player, axis=0)): # this checks if any column contains all positions equal to player
        return True
    else:
        return False

col_win(board, 1)

False

Finally, create a function diag_win(board, player) that takes the player (integer) and determines if any diagonal consists of only their marker.

Have it return True if this condition is met and False otherwise.
Note that board is modified. Call diag_win to check if Player 2 has a complete diagonal.

In [8]:
board[1,1] = 2
def diag_win(board, player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        # np.diag returns the diagonal of the array
        # np.fliplr rearranges columns in reverse order
        return True
    else:
        return False

diag_win(board, 2)

True

Create a function evaluate(board) that uses row_win, col_win, and diag_win functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.

Call evaluate to see if either player has won the game yet.

In [9]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)

2

Create a function play_game() that:

- Creates a board.

- Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.

- Evaluates the board for a winner after each placement.

- Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).

Call play_game 1000 times, and store the results of the game in a list called results. Use random.seed(1) so we can check our answer!
How many times does Player 1 win out of 1000 games?

In [10]:
random.seed(1)

def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_game() for i in range(1000)]
results.count(1)

591

Create a function play_strategic_game(), where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.

Call play_strategic_game 1000 times.
Set the seed to 1 using random.seed(1) again.
Lets print how many times does Player 1 win out of 1000 games with this new strategy?

In [11]:
random.seed(1)

def play_strategic_game():
    board, winner = create_board(), 0
    board[1,1] = 1
    while winner == 0:
        for player in [2,1]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_strategic_game() for i in range(1000)]
results.count(1)

716